--- #YAML:1.0
name: CGI-Application-Plugin-ConfigAuto
version: 1.33
author:
  - Mark Stosberg <mark@summersault.com>
abstract: |-
  Plugin that adds Config::Auto support to CGI::Application
license: perl
requires:
  CGI::Application: 0
  Carp: 0
  Config::Auto: 0
provides:
  CGI::Application::Plugin::ConfigAuto:
    file: lib/CGI/Application/Plugin/ConfigAuto.pm
    version: 1.33
generated_by: Module::Build version 0.2611
